### ISSUE TITLE
Crash when used with Indium [1.18.1]

### ISSUE THREAD

**Issue by MarioAndWeegee3** [vram-guild/frex#5]
[Crash report](https://pastebin.com/51GkmMh1)

**Comment by supsm** [comment]
Frex is a different renderer that is incompatible with ingido (from indium), which is what the crash report says. This cannot be compatible with indium and probably never will. I also don't see a need for it.

**Comment by grondag** [comment]
Currently Indium is not compatible.  I'd like to see integration of FREX with Indium/Sodium/Iris but there is no defined path or timetable for that.
